### ISSUE TITLE
Issues fetching documents

### ISSUE THREAD

**Issue by fitchtravis** [richarvey/getAWSdocs#10]
Hi,

I've update my repo and rerun ./getAWSdocs.py, yet nothing is still being downloaded.

After running the python script, the documentation directory is not being populated with any PDFs

Example run:

~/code/getAWSdocs$ ./getAWSdocs.py -d
Downloading Docs
Generating PDF list (this may take some time)
URI:  /ec2/?id=docs_gateway
Guide info url: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/cli/latest/reference/ec2/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/autoscaling/ec2/userguide/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/cli/latest/reference/autoscaling/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/autoscaling/ec2/APIReference/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/vm-import/latest/userguide/meta-inf/guide-info.json
URI:  /batch/?id=docs_gateway
Guide info url: http://docs.aws.amazon.com/batch/latest/userguide/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/batch/latest/APIReference/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/cli/latest/reference/batch/meta-inf/guide-info.json
URI:  /ecr/?id=docs_gateway
Guide info url: http://docs.aws.amazon.com/AmazonECR/latest/userguide/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/AmazonECR/latest/APIReference/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/cli/latest/reference/ecr/meta-inf/guide-info.json
URI:  /ecs/?id=docs_gateway
Guide info url: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/AmazonECS/latest/userguide/meta-inf/guide-info.json
Guide info url: http://docs.aws.amazon.com/AmazonECS/latest/APIReference/meta-inf/guide-info.json

**Comment by SandeepKaundinya** [comment]
I've the same issue while downloading the documentation. But, code works with the download of the whitepapers. Issue is only with the download of documentation.

**Comment by richarvey** [comment]
v1.2 shouldn't have this issue
